### ISSUE TITLE
Проектирование REST API

### ISSUE THREAD

**Issue by mikhailborodin** [thinknetica-django-lab-02/realzuy#100]
**Что?**

Рассказать о правилах построения апи по rest архитектуре
**Задачи**
1. Спроектировать апи для своего проекта по rest архитектуре
**Ресурсы**
https://docs.microsoft.com/ru-ru/azure/architecture/best-practices/api-design

**Comment by realzuy** [comment]
Mikhail Borodin, [05.05.21 16:08]
14.1 закрываете без пул реквеста
